name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build APK with Buildozer Action
        uses: ArtemSydoryk/buildozer-action@v1
        with:
          buildozer_version: 'stable'
          command: buildozer -v android debug
          repository_path: '.'

      - name: Upload Finished APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HackerCalculator-APK
          path: bin/*.apk
